### PR TITLE
Resolves #23

### LINKED ISSUE #23: Runtime Error in Analyze Step
Got following error message in this step, it seems related to tensor dimension, anything related to the version of pytorch? 
```bash
python scripts/mutrans.py --vary-holdout
```
   509512 step 10000 L=12.7628 RS=0.08 IS=1.46 RLS=0.0165 ILS=96.8
```bash
Traceback (most recent call last):
  File "./python3.8/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
  File "./python3.8/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "./python3.8/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "mutrans.py", line 541, in model
    pc_rate_loc = rate_loc.expand(P, C).reshape(-1)
RuntimeError: expand(torch.cuda.FloatTensor{[1000, 1, 1, 1, 3000]}, size=[5, 3000]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (5)
```

### PR DESCRIPTION
**Pull request by fritzo**
Resolves #23

Avoids vectorization to avoid tensor shape errors

### CODE REVIEW

**Comment by fritzo** [comment]
Looks like linting is failing due to the new file generate_epiToPublicAndDate.py. @bkotzen could you add that file to the flake8 ignores in setup.cfg so CI is unblocked?

**Comment by bkotzen** [comment]
sure thing! does it need the `:E226` suffix?

**Comment by bkotzen** [comment]
It seems to be clearing flake8 and getting hung on black now? Is there a different place for me to deal with that?

**Comment by fritzo** [comment]
Thanks @bkotzen. I ran `make format` to fix the `black` errors, then added some `type: ignore` stuff to fix the subsequent `mypy` errors.

**Comment by fritzo** [comment]
@bkotzen could you add me as a maintainer or contributor in repo settings, so I can (1) retry failed builds, (2) add tags to issues?

**Comment by fritzo** [comment]
😅 phew this PR required a whole lot of maintenance fixes!  @bkotzen could you please take another look?  Thanks!

**Comment by bkotzen** [comment]
Looks good to me, thanks for weeding through all this! I don't think I have access to repository settings; I can try to chase down who does if you would still like to be maintainer / contributor?

**Pull request merged**
